noun1 = input("Name a noun ")
adjectiveer1 = input("Name an adjective ending in er ")
verb1 = input("Name a verb ")
name1 = input("Name a name ")
verbing1 = input("Name a verb ending in ing ")
adjectiveer2 = input("Name an adjective ending in er ")
noun2 = input("Name a noun ")
name2 = input("Name a name ")
preposition1 = input("Name a posional preposition ")
verb2 = input("Name a verb ")
adjectiveest1 = input("Name a adjective ending in est ")
emotion1 = input("Name a self emotion ")
print("One day {} was {} {} a(n) {} and decided that {} and I should have a competition where we have to {} {} a(n) {} and then {} {} a(n) {} for 5 minutes and whoever could do it the {} wins. So {} texted {} about the competition and asked him/her if (s)he wanted to compete. Sure! {} said as (s)he rode his/her bike to {}'s house. {} was {} that (s)he was invited. as soon as (s)he made it {} noticed that {} looked {} than normal. {} said that (s)he's like that because it makes him/her {} {}. {} was intimidated because of that, but was still confident. they started the compitition. It was a close call, but {} won!\n>")
