from turtle import Turtle

one = Turtle()
two = Turtle()
three = Turtle()
four = Turtle()
five = Turtle()
six = Turtle()
seven = Turtle()
eight = Turtle()


one.pensize(1)
two.pensize(1)
three.pensize(1)
four.pensize(1)
five.pensize(1)
six.pensize(1)
seven.pensize(1)
eight.pensize(1)


one.speed(0)
two.speed(0)
three.speed(0)
four.speed(0)
five.speed(0)
six.speed(0)
seven.speed(0)
eight.speed(0)


three.pu()
four.pu()
five.pu()
six.pu()
one.forward(100)
two.left(90)
two.forward(100)
three.backward(10)
four.backward(10)
five.backward(10)
six.backward(10)
four.pd()
three.pd()
five.pd()
six.pd()
two.right(90)
four.right(90)
one.left(90)
three.right(90)
five.right(90)
six.right(90)
one.forward(100)
two.forward(100)
three.forward(10)
four.forward(10)
five.forward(10)
six.forward(10)
three.left(90)
four.backward(120)
six.backward(120)
three.forward(120)
three.left(90)
four.left(90)
four.forward(120)
three.forward(120)
three.backward(120)
four.left(90)
for count in range(1, 41):
    six.backward(1)
    three.forward(1)
    four.forward(1)
    six.right(90)
    three.right(90)
    four.right(90)
    six.backward(1)
    three.forward(1)
    four.forward(1)
    six.left(90)
    three.left(90)
    four.left(90)
three.forward(120)
four.left(90)
four.forward(120)
one.pu()
one.forward(10)
for count in range(1, 6):
    one.forward(1)
    one.right(90)
    one.forward(1)
    one.left(90)
one.pd()




